### ISSUE TITLE
Plotting stuff example gives `ValueError'

### ISSUE THREAD

**Issue by chenyulue** [proplot-dev/proplot#356]
I'm learning proplot according to the documents. When trying [Plotting stuff](https://proplot.readthedocs.io/en/latest/basics.html#Plotting-stuff) example, it gives a `ValueError: DiscreteNorm is not invertible.`

My maplotlib and proplot version are as follows:

```python
In [1]: matplotlib.__version__
Out[1]: '3.5.1'

In [2]: pplt.__version__
Out[2]: '0.9.5.post301'
```

I'm not sure whether this is related to the incompatibility with matplotlib of version 3.5.1.

**Comment by lukelbd** [comment]
Seems this error is fixed (but not sure where/when). You might have been using a "dev" version that accidentally included a new bug.
