### ISSUE TITLE
ax.step where parameter 

### ISSUE THREAD

**Issue by austin-hoover** [proplot-dev/proplot#359]
### Description

In `ax.step`, the 'where' parameter doesn't do anything in proplot.

### Steps to reproduce

```python
import numpy as np
import proplot as pplt

x = np.linspace(-5.0, 5.0, 11)
y = np.exp(-0.5 * x**2)

fig, axes = pplt.subplots(nrows=3, figsize=(4.0, 3.0), spany=False)
for ax, where in zip(axes, ['pre', 'post', 'mid']):
    ax.step(x, y, where=where, color='black', alpha=0.2)
    ax.scatter(x, y, color='black', marker='.')
    ax.format(ylabel=where)
```
![pplt](https://user-images.githubusercontent.com/58012334/168488146-810abad6-aeb9-4958-849a-27d784623fa1.png)

**Expected behavior**: The `where` parameter should shift the locations of the steps.

**Actual behavior**:  The `where` parameter does not shift the locations of the steps.

### Equivalent steps in matplotlib

```python
import numpy as np
from matplotlib import pyplot as plt

x = np.linspace(-5.0, 5.0, 11)
y = np.exp(-0.5 * x**2)

fig, axes = plt.subplots(nrows=3, figsize=(4.0, 3.0), sharex=True)
for ax, where in zip(axes, ['pre', 'post', 'mid']):
    ax.step(x, y, where=where, color='black', alpha=0.2)
    ax.scatter(x, y, color='black', marker='.')
    ax.set_ylabel(where)
```
![plt](https://user-images.githubusercontent.com/58012334/168488151-df71e0ad-8bfd-4f6b-a4ef-044a2ec888e7.png)

### Proplot version
matplotlib=3.4.3
proplot=0.9.5

**Comment by pguenth** [comment]
can confirm using proplot=0.9.5.post301 and matplotlib=3.5.2

**Comment by AWSisco** [comment]
If you need an immediate solution to this using only Proplot, you can use the ```drawstyle``` argument with ```ax.plot``` instead to achieve the desired behavior.

```
import proplot as pplt
import numpy as np

x = np.linspace(-5.0, 5.0, 11)
y = np.exp(-0.5 * x**2)

fig, axes = pplt.subplots(nrows=3, figsize=(4.0, 3.0), spany=False)
for ax, drawstyle in zip(axes, ['steps', 'steps-post', 'steps-mid']):
    ax.plot(x, y, drawstyle=drawstyle, color='black', alpha=0.2)
    ax.scatter(x, y, color='black', marker='.')
    ax.format(ylabel=drawstyle, grid=False, ylocator=1)
```

![drawstyle](https://user-images.githubusercontent.com/37667176/180652223-84498442-bb2f-4a68-8d91-56d6c7036e94.png)
