### ISSUE TITLE
incorrect position of ylabel

### ISSUE THREAD

**Issue by Yefee** [proplot-dev/proplot#373]
### Description

When having 2 axes, the ylabel of top panel appears in the middle of the left figure.

### Steps to reproduce
```python
hydl = np.sin(2*np.arange(0, 60, 0.1))
vwsdl = np.cos(2*np.arange(0, 60, 0.1))

fig, axs = pplt.subplots(ncols=1, nrows=2)
axs[0].plot(hydl)
axs[1].plot(vwsdl)
axs[0].format(title='AA', titleweight='bold', ylabel='CC')
axs[1].format(title='BB', titleweight='bold', ylabel='DD')
```

**Expected behavior**: 
**CC** appears at the left of top panel
**DD**appears at the left of bottom panel

**Actual behavior**: 
**CC** appears in the middle
<img width="404" alt="image" src="https://user-images.githubusercontent.com/6420873/180356652-13d9dca5-3c80-4a33-8dac-b0d084c33d4a.png">

### Equivalent steps in matplotlib

Please try to make sure this bug is related to a proplot-specific feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
# your code here, if applicable
import matplotlib.pyplot as plt
fig, axs = plt.subplots(ncols=1, nrows=2)
axs[0].plot(hydl)
axs[0].set_ylim([-1.6, 1.6])
axs[1].plot(vwsdl)
axs[1].set_ylim([-2, 2])
axs[0].set_ylabel('CC')
axs[1].set_ylabel('DD')
```
<img width="471" alt="image" src="https://user-images.githubusercontent.com/6420873/180356701-08671592-f244-4481-b17d-68232100b8c5.png">

### Proplot version
import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)
3.4.3
0.9.5

**Comment by syrte** [comment]
This is actually the behavior expected from the proplot side, though I agree that it is a bit counter-intuitive.
When initializing the figure, you may add "sharey=False" to disable the label sharing:

    fig, axs = pplt.subplots(ncols=1, nrows=2, sharey=False)

It should fix your problem.

**Comment by Yefee** [comment]
Good to know! Thanks!

**Comment by lukelbd** [comment]
Thanks for the help @syrte. You're right this is counterintuitive -- I'll consider disabling `share` and `span` in the next version by default... or maybe I'll even try to automatically detect whether users want shared labels depending on whether they separately apply labels to individual axes (as in your example) or make single `axs.format(xlabel='label')` calls.
