### ISSUE TITLE
How to centre the colorbar of a figure？

### ISSUE THREAD

**Issue by donglx2018** [proplot-dev/proplot#388]
### Description

An inset colorbar can not centred. 
The loc parameter has no centering option.

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

    import proplot as pplt
    import numpy as np

    x = np.array([1,2,3,4,5,6])
    y = np.array([1, 2])
    data = [[np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],[1,2,2,1,3,4]]

    with pplt.rc.context({'cmap': 'Grays', 'cmap.levels': 21}):
        # Figure
        fig = pplt.figure(refwidth=2.3, share=False)
        axs = fig.subplots(ncols=1)
        axs.format(xlabel='xlabel', ylabel='ylabel',xlocator=1, ylocator=1, )
        hs=axs[0].pcolor( data, cmap='colorblind', levels=pplt.arange(0, 9,1))
        axs.colorbar(hs, loc='ll',length=12,) 

**Expected behavior**:
I want the colorbar in the figure to be centred.
**Actual behavior**: 
![image](https://user-images.githubusercontent.com/51145210/189163923-3b0da569-452f-499e-932b-aec77393c609.png)

### Proplot version
matplotlib version is 3.3.4
proplot version is 0.9.5

**Comment by AWSisco** [comment]
I don't think a centered colorbar is currently supported by proplot.

However, I've occasionally used ```inset_axes``` and ```loc='fill'``` as a hacky way to place colorbars at my own user-specified locations within a subplot. You will lose the frame around your colorbar if you take this route, but maybe it gets you closer to what you're looking for.

```python
import proplot as pplt
import numpy as np

data = [[np.nan,np.nan,np.nan,np.nan,np.nan,np.nan],[1,2,2,1,3,4]]

fig, ax = pplt.subplots(aspect=(1,1))
ax.format(xlabel='xlabel',ylabel='ylabel',xlocator=1,ylocator=1,grid=False)

p = ax.pcolor(data,levels=pplt.arange(0,9,1),cmap='colorblind')

iax = ax.inset_axes([0.15,0.1,0.7,0.05],zoom=False)
iax.colorbar(p,loc='fill',locator=3)
```
![cbar](https://user-images.githubusercontent.com/37667176/189492039-8e3a4be7-b89a-468c-b93c-ff689c99da8a.png)

**Comment by donglx2018** [comment]
@AWSisco Thanks. The method you provided should work, but the following error occurs when executing the code.

> 
> Traceback (most recent call last):
> 
>   File "C:\Users\Administrator\未命名1.py", line 18, in <module>
>     iax.colorbar(p,loc='fill',locator=3)
> 
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\proplot\axes\base.py", line 2440, in colorbar
>     cb = self._draw_colorbar(mappable, values, loc=loc, **kwargs)
> 
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\proplot\axes\base.py", line 2239, in _draw_colorbar
>     cax, kwargs = self._parse_outer_colorbar(**kwargs)
> 
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\proplot\axes\base.py", line 1892, in _parse_outer_colorbar
>     raise RuntimeError('Axes must be a subplot.')
> 
> RuntimeError: Axes must be a subplot.

The generated figure is as follows.
![image](https://user-images.githubusercontent.com/51145210/189800655-0da349dc-2ed4-4d4a-acd4-de1b766c0a99.png)

**Comment by donglx2018** [comment]
@AWSisco Thanks! It works.
