### ISSUE TITLE
Can not add hatch with bar plot.

### ISSUE THREAD

**Issue by jwy-wbe** [proplot-dev/proplot#389]
### Description

Can not add hatch with bar plot.

### Steps to reproduce

```python
import numpy as np 
import proplot as pplt
pplt.rc['hatch.color'] = 'k'
fig, ax = pplt.subplots(refwidth=4, refheight=3)
ax.format(ylabel=f"degC/month",xlabel = 'Terms',grid=False,suptitle_kw = {"fontsize":12})
ax.bar(np.arange(10),np.random.rand(10),negpos=True,width = 0.35,hatch = '*')
```
![output](https://user-images.githubusercontent.com/52997955/191272482-67f128f7-907f-4de3-a0b6-328fa9cbe212.png)

### Equivalent steps in matplotlib

A same way in matplotlib, which can show the stars

```python
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(4,3))
ax = fig.add_subplot(111)
ax.bar(np.arange(10),np.random.rand(10),width = 0.35,hatch = '*')
```
![output](https://user-images.githubusercontent.com/52997955/191273124-9a6cd8f2-9ca6-41a2-bfd0-67b4b139b116.png)

### Proplot version

matplotlib:3.4.3
proplot:0.9.5

**Comment by zxdawn** [comment]
You can specify the edgecolor and hatch will take it automatically.

```
import numpy as np 
import proplot as pplt
pplt.rc['hatch.color'] = 'k'
fig, ax = pplt.subplots(refwidth=4, refheight=3)
ax.format(ylabel=f"degC/month",xlabel = 'Terms',grid=False,suptitle_kw = {"fontsize":12})
ax.bar(np.arange(10),np.random.rand(10),negpos=True,width = 0.35, edgecolor='k', hatch='*')
```

<img width="544" alt="image" src="https://user-images.githubusercontent.com/30388627/191276253-c691c839-bbec-47bb-9791-ac119bdfbbe7.png">

**Comment by jwy-wbe** [comment]
> You can specify the edgecolor and hatch will take it automatically.
> 
> If you only want the hatch, you can set edgewidth=0.
> 
> ```
> import numpy as np 
> import proplot as pplt
> pplt.rc['hatch.color'] = 'k'
> fig, ax = pplt.subplots(refwidth=4, refheight=3)
> ax.format(ylabel=f"degC/month",xlabel = 'Terms',grid=False,suptitle_kw = {"fontsize":12})
> ax.bar(np.arange(10),np.random.rand(10),negpos=True,width = 0.35, edgecolor='k', hatch='*')
> ```
> 
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/30388627/191276253-c691c839-bbec-47bb-9791-ac119bdfbbe7.png">

Thanks a lot. I will try it later. This is an amazing project by the way.

**Comment by lukelbd** [comment]
This seems to be fixed in the latest "dev" version (install with `pip install git+https://github.com/proplot-dev/proplot`). I believe I used to override the edgecolor in some way, but now I just revert to matplotlib's default behavior.

With your example:

```python
import numpy as np
import proplot as pplt
pplt.rc['hatch.color'] = 'k'
fig, ax = pplt.subplots(refwidth=4, refheight=3)
ax.format(ylabel=f"degC/month",xlabel = 'Terms',grid=False,suptitle_kw = {"fontsize":12})
ax.bar(np.arange(10),np.random.rand(10),negpos=True,width = 0.35,hatch = '*')
```

v0.9.7 output:

![iTerm2 zmn8dC tmp1e16d1um](https://user-images.githubusercontent.com/19657652/228393708-91c9e8e7-1aed-4586-96de-034692b32c3d.png)

dev version output:

![iTerm2 x2KKPq tmp3mvujtoe](https://user-images.githubusercontent.com/19657652/228393580-2b593f0f-3b6c-42ba-8b93-54333ae7784f.png)
