### ISSUE TITLE
When subplotting, all lines are plotted only in the last image plot

### ISSUE THREAD

**Issue by Robotatron** [proplot-dev/proplot#391]
Very basic example code, I am plotting images for each axis. Additionally, for each axis, I am plotting some lines with `coco.plot.showAnns(anns)` which in turn calls several `pplt.pyplot.plot()` functions

For some reason, instead of having lines plotted in each image, all them are plotted only in the last one?

![image](https://user-images.githubusercontent.com/95919873/192000184-1684e1e2-5ec5-46cd-bdc5-6d23aa638c47.png)

**Comment by zxdawn** [comment]
You can set all axis without gridline and then specify the last one you want:

```
import proplot as pplt

fig, axs = pplt.subplots(nrows=2, ncols=2)

axs.format(grid=False)
axs[-1].format(grid=True)
```
<img width="672" alt="image" src="https://user-images.githubusercontent.com/30388627/192001348-e72b12cc-69c7-42e2-a02e-74cea607effa.png">

**Comment by Robotatron** [comment]
@zxdawn My question was not about gridlines. The problem I am having is  that the plot from `coco.plot.showAnns(anns)` which is inside the loop it plotted only in the last image. It should have plotted on every image, instead all plots are only in the last image.

**Comment by Robotatron** [comment]
What I expect:
![image](https://user-images.githubusercontent.com/95919873/192004810-df5997f1-3d94-4064-b69f-bfb590120f08.png)

Instead it plots everything onto the last image:
![image](https://user-images.githubusercontent.com/95919873/192004881-e83901b0-7494-4a30-b282-d769d6a5a299.png)

**Comment by Robotatron** [comment]
Better example. I would expect the colored horizontal line to be plotted in every image. Instead all 4 are plotted only in the last image.
![image](https://user-images.githubusercontent.com/95919873/192005903-4fe0bb6a-5da6-4fc8-81c4-92a9daab7aff.png)

Expectation:
![image](https://user-images.githubusercontent.com/95919873/192006012-935619a6-543a-4b4d-91f7-6022f46adfff.png)

**Comment by Robotatron** [comment]
Figured it out after watching https://www.youtube.com/watch?v=6gdNUDs6QPc
Basically, `plot_fine()` has to be provided an instance of the Axes, then it works fine!

![image](https://user-images.githubusercontent.com/95919873/192050629-7e3f73f2-4d39-4190-a0d1-966d323056f8.png)
