### ISSUE TITLE
TypeError: ufunc 'isfinite' not supported for the input types

### ISSUE THREAD

**Issue by lkugler** [proplot-dev/proplot#393]
### Description

I want to warn others that this combination of Matplotlib + proplot + pandas doesnt work.

### Steps to reproduce

```python
import numpy as np
import datetime as dt
import pandas as pd
import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as plt
import proplot as pplt

fig, ax = pplt.subplots()   # <-------------------------  pplt instead plt

df = pd.DataFrame(index=pd.date_range(start=dt.datetime(2000,1,1), end=dt.datetime(2000,1,1, 2), freq='1H'),
                    data=dict(test=np.array([1.,2.,3.])))
df.plot(ax=ax)
```
Produces 
```
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Equivalent (working) steps in matplotlib
```python
import numpy as np
import datetime as dt
import pandas as pd
import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as plt

fig, ax = plt.subplots() 

df = pd.DataFrame(index=pd.date_range(start=dt.datetime(2000,1,1), end=dt.datetime(2000,1,1, 2), freq='1H'),
                    data=dict(test=np.array([1.,2.,3.])))
df.plot(ax=ax)
```

### Proplot version
Matplotlib version 3.4.3 (same for 3.5.3)
proplot 0.9.5
Pandas 1.3.4

**Comment by lkugler** [comment]
Converting the input to np.datetime64 should not be necessary, as it is not required with default matplotlib, right?

**Comment by lkugler** [comment]
## Solution: Install newest (dev) version
`pip install git+https://github.com/proplot-dev/proplot.git`

**Comment by lukelbd** [comment]
The latest stable proplot version 0.9.7 finally addresses this issue (#309).

**Comment by julian-belina** [comment]
I have just updated proplot to version 0.9.7 from conda forge but the error remains, unfortunately.

**Comment by lukelbd** [comment]
Oh you're right, sorry. Lumped this in with a bunch of other proplot version issue threads I was reviewing. Seems this is actually related to #320 (which was fixed on master).
