### ISSUE TITLE
Have you put the project on hold?

### ISSUE THREAD

**Issue by Mickychen00** [proplot-dev/proplot#401]
Hi, now I can use proplot based on matplotlib==3.4.3 and numpy = 1.21.0
But now matplotlib and numpy has updated a lot. For example, if I keep matplotlib to 3.4.3, I will encounter "numpy has no attibute int" problem when I use numpy version greater than 1.21.0.

I think proplot is an awesome package and helped me to publish two papers. 
Will you continue to update?

**Comment by Sangwon91** [comment]
That's right. It's a really nice library.
In order to save this library, I will have to fork and solve all compatibility problems.

**Comment by Mickychen00** [comment]
Thanks very much. Proplot is a high-efficient tool for scientific plotting. It's a pity if it's not updated anymore. L
ooking forward to your new contributions.

Best wishes.

**Comment by gepcel** [comment]
I'm not a maintainer of this package, but I like it very much and used it a lot. I've noticed that this issue isn't answered yet. I'll copy some info from the maintainer from other issues:

```
I just submitted a release v0.9.7 to pypi that updates v0.9.5 with the requirement matplotlib>=3.3.0,<3.5.0 and addresses numpy's deprecation of python-type aliases like np.int (v0.9.6 didn't include the numpy fixes). Now pip install proplot should enforce a compatible matplotlib version, as I think conda install proplot already does.

Originally I was hoping to do the v0.10.0 release that adds matplotlib 3.5.X compatibility + other fixes/improvements/tests. But obviously the above timeline didn't work out -- I've had to take another hard step back from proplot as I finish my PhD.

I still personally use proplot every day in my work, and I plan to continue using it throughout my career, so I have no plans to abandon this project. Should finally have time to work on proplot this late spring/summer, and I'm looking into funding sources + options for building more of a community around this project (i.e., not just me -- hence the move to the "proplot-dev" organization) so that development can be less erratic going forward.
```

Let us all together hope that the maintainer will have the time and chance to update this package as soon as possible. I even want to update this by myself. But I too have no time for this, at least for the next few months.

Thanks a lot for this wonderful package, it's really helpful, @lukelbd.

**Comment by syrte** [comment]
+1: I love proplot as well! It is really the way to design the user interface.

**Comment by lukelbd** [comment]
Thanks for the kind words everyone! It's mostly on hold for now, but planning to return to a more regular development pace this summer.
