### ISSUE TITLE
Bug: contour does not work for 2 levels

### ISSUE THREAD

**Issue by syrte** [proplot-dev/proplot#407]
### Description

contour does not work for 2 levels in proplot.

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
import proplot as pplt
from scipy.stats import multivariate_normal
import numpy as np

fig, ax = pplt.subplot()
x, y = np.mgrid[-2:2:50j, -2:2:50j]
z = multivariate_normal([0, 0], [[2.0, 0.3], [0.3, 0.5]]).pdf(np.dstack([x, y]))
ax.contour(x, y, z, levels=np.linspace(0, z.max(), 4)[1:-1])
```
I got this with warnings:
```
/path/lib/python3.8/site-packages/proplot/colors.py:2284: RuntimeWarning: invalid value encountered in true_divide
  return y0 + (y1 - y0) * (x - x0) / (x1 - x0)
```
and an **empty** figure.

**Actual behavior**: [What actually happened]
![image](https://user-images.githubusercontent.com/7038335/224503742-23fef6df-5c44-4fa5-ac8b-4dd0ca65726f.png)

If I use 3 levels:
```python
import proplot as pplt
from scipy.stats import multivariate_normal
import numpy as np

fig, ax = pplt.subplot()
x, y = np.mgrid[-2:2:50j, -2:2:50j]
z = multivariate_normal([0, 0], [[2.0, 0.3], [0.3, 0.5]]).pdf(np.dstack([x, y]))
ax.contour(x, y, z, levels=np.linspace(0, z.max(), 5)[1:-1])
```
It works well.
![image](https://user-images.githubusercontent.com/7038335/224503765-238ab0d2-0bfa-43d9-a851-23f5ee2ed5df.png)

Also I confirm that 2 levels work in matplotlib. 
It confused me for quite a while when I convert my matplotlib code to proplot.

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)` here.

3.4.3
0.9.5.post333

**Comment by syrte** [comment]
A general temporary workaround for functions that do not work as expected: call the matplotlib version of the plotting function, for example, for the contour function in the above example
```
mpl.axes._axes.Axes.contour(ax, x, y, z, levels=np.linspace(0, z.max(), 4)[1:-1])
```

**Comment by lukelbd** [comment]
Good workaround idea -- `mpl.axes.Axes` should also work. This is a problem with proplot's `DiscreteNorm`. Fix was pretty quick.

**Comment by syrte** [comment]
Thanks for the quick fix!
