### ISSUE TITLE
How to set the order of 'abc'? 

### ISSUE THREAD

**Issue by HaoLi2025** [proplot-dev/proplot#427]
### Description

[Description of the bug or feature.]

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
# your code here
# we should be able to copy-paste this into python and exactly reproduce your bug
```

**Expected behavior**: [What you expected to happen]

**Actual behavior**: [What actually happened]

### Equivalent steps in matplotlib

Please try to make sure this bug is related to a proplot-specific feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
# your code here, if applicable
import matplotlib.pyplot as plt
```

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)` here.

**Comment by lukelbd** [comment]
A-b-c order is determined by the `number` passed to the subplot during creation. The [docs have more info](https://proplot.readthedocs.io/en/stable/subplots.html#A-b-c-labels).
